# Generated by Django 2.2.5 on 2019-09-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Account')),
            ],
        ),
    ]
